baseURL = "https://silvermecanica.com"
languageCode = "es-mx"
title = "Silver Mecánica"
theme = "sicily"
brandingTitle = "SM"

googleAnalytics = "G-GNRDHBP7SG"
languageName = "Es"
paginate = "10"
summaryLength = "15"

[markup.goldmark.renderer]
unsafe = true

[[menu.company]]
URL = "acerca_de"
name = "Acerca de nosotros"


[[menu.main]]
URL = "pricing"
name = "Paquetes"
weight = 1
[[menu.main]]
URL = "contacto"
name = "Contacto"
weight = 2
[[menu.main]]
URL = "faq"
name = "FAQ"
weight = 3

[[menu.info]]
URL = "pricing"
name = "Paquetes"
[[menu.info]]
URL = "faq"
name = "FAQ"
[[menu.info]]
URL = "privacy-policy"
name = "Política de Privacidad"


[params.company]
address = "Cumbres de Maltrata 486, Niños héroes"
city = "Benito Juárez, CDMX"
country = "México"
email = "silvermecanica@gmail.com"
phone = "55 7411 2448"
[params.navigation_button]
enable = true
label = "Ponte en contacto"
link = "contacto"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/custom/clean-footer.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[params.preloader]
enable = false
preloader = ""

[[params.footer]]
rol_email = "silvermecanica@gmail.com"
rol_name = "Jefe de Taller"
rol_representative = "Jesús Uriel Patricio Moreno"
